-- ============================================================
-- SEED DATA: 557 CANCIONES PARA KARAOKE JL MUSIC
-- ============================================================

INSERT INTO canciones (id, numero, titulo, artista, genero, video_url) VALUES
(1, 1, 'Lo Aprendi De Ti', 'Ha Ash', 'Pop Latino / Urbano', '/video/01 Ha Ash _ Lo Aprendí de Ti karaoke(360P)_1.mp4'),
(2, 2, 'Si Nos Dejan', 'Jose Alfredo Jimenez', 'Ranchera / Mariachi', '/video/02 José Alfredo Jiménez Si nos dejan (360P)_1.mp4'),
(3, 3, 'Lo Que Un Dia Fue No Sera', 'Jose Jose', 'Balada / Romántica', '/video/03  José José - Lo que un día fue no será(360P)_1.mp4'),
(4, 4, 'No Tengo Dinero', 'Juan Gabriel', 'Balada / Romántica', '/video/04  Juan Gabriel - No tengo dinero(360P)_1.mp4'),
(5, 5, 'Te He Perdido', 'Henry Stephen', 'Balada / Romántica', '/video/05 Te He Perdido - Henry Stephen.mp4'),
(6, 6, 'Abrazame', 'Alejandro Fernandez', 'Variado / Éxitos', '/video/06 Alejandro Fernandez   Abrazame    HQ(360P).mp4'),
(7, 7, 'Son De Amores', 'Andy Y Luca', 'Variado / Éxitos', '/video/07 Andy Y Lucas - Son De Amores _(360P).mp4'),
(8, 8, 'Adoro', 'Armando Manzanero', 'Balada / Romántica', '/video/08 Armando Manzanero - Adoro (480P).mp4'),
(9, 9, 'Contigo Aprendi', 'Armando Manzanero', 'Balada / Romántica', '/video/09 Armando Manzanero - Contigo Aprendi (480P).mp4'),
(10, 10, 'Parece Que Fue Ayer', 'Armando Manzanero', 'Balada / Romántica', '/video/10 Armando Manzanero - Parece Que Fue Ayer  (720P_HD).mp4'),
(11, 11, 'Otoño', 'Jose Luis Perales', 'Balada / Romántica', '/video/11 Canción de otoño - José Luis Perales.mp4'),
(12, 12, 'Aquel Viejo Motel', 'David Pabon', 'Variado / Éxitos', '/video/12 David Pabon - Aquel Viejo Motel.mp4'),
(13, 13, 'De Que Manera Te Olvido', 'Vicente Fernandez', 'Ranchera / Mariachi', '/video/13 De que Manera te Olvido al Estilo de Vicente Fernandez.mp4'),
(14, 14, 'Volvere', 'Diego Verdaguer', 'Variado / Éxitos', '/video/14 VOLVERE..mp4'),
(15, 15, 'Demasiado Niña', 'Eddy Herrera', 'Merengue', '/video/15 Demasiado Niña - Eddy Herrera.mov'),
(16, 16, 'Juanito Alimaña', 'Hector Lavoe', 'Salsa', '/video/16 Hector Lavoe - Juanito Alimaña.mp4'),
(17, 17, 'Corre', 'Jesse', 'Pop Latino / Urbano', '/video/17 Jesse _ Joy - Corre.mp4'),
(18, 18, 'Voy A Perder La Cabeza Por Tu Amor', 'Jose Luis Rodriguez', 'Balada / Romántica', '/video/18 Jose Luis Rodriguez - Voy A Perder La Cabeza Por Tu Amor.mp4'),
(19, 19, 'Te Lo Pido Por Favor', 'Juan Gabriel', 'Balada / Romántica', '/video/19 JUAN GABRIEL_ Te lo pido por favor.mp4'),
(20, 20, 'Hoy Tengo Ganas De Ti', 'Alejandro Fernandez', 'Variado / Éxitos', '/video/20 Alejandro Fernández - Hoy tengo ganas de ti.mp4'),
(21, 21, 'Novillero', 'Javier Solis', 'Ranchera / Mariachi', '/video/21 Javier Solís - Novillero(240P)(240P).mp4'),
(22, 22, 'Silverio', 'Javier Solis', 'Ranchera / Mariachi', '/video/22 Javier Solís - Silverio(144P).mp4'),
(23, 23, 'Besame', 'Ricardo Montaner', 'Pop Latino / Urbano', '/video/23 Bésame - Ricardo Montaner _(480P).mp4'),
(24, 24, 'Como Yo Nadie Te Amado', 'Bon Jovi', 'Rock / Pop-Rock', '/video/24 Como yo nadie te amado (Bon Jovi)(480P).mp4'),
(25, 25, 'El Gitano Señoron', 'Varios', 'Variado / Éxitos', '/video/25 EL GITANO SEÑORON.mp4'),
(26, 26, 'No Te Puedo Querrer', 'Carmelo Larrea', 'Variado / Éxitos', '/video/26 Pasodoble - No te puedo querer(240P)(240P).mp4'),
(27, 27, 'Resistire', 'Duo Dinamico', 'Balada / Romántica', '/video/27 Resistiré - Dúo Dinámico (Full)(480P).mp4'),
(28, 28, 'Taboga', 'Oscar De Leon', 'Salsa', '/video/28 Taboga - Oscar de Leon.mp4'),
(29, 29, 'Un Velero Llamado Libertad', 'Jose Luis Perales', 'Balada / Romántica', '/video/29 Un Velero LLamado Libertad(480P).mp4'),
(30, 30, 'Tu Amor Me Hace Bien', 'Marck Antonhy', 'Salsa', '/video/30 Marc Anthony Tu Amor Me Hace Bien.mp4'),
(31, 31, 'Matalas', 'Alejandro Fernandez', 'Variado / Éxitos', '/video/31 MATALAS.mp4'),
(32, 32, 'Ni Se Compra Ni Se Vende', 'Billos Caracas Boys', 'Merengue', '/video/32 Ni se compra ni se vende Billo_s Caracas Boys.mp4'),
(33, 33, 'No Volvere', 'Pedro Infante', 'Ranchera / Mariachi', '/video/33 No Volveré -  Pedro Infante.mp4'),
(34, 34, 'Sobredosis De Amor', 'Los Titanes', 'Salsa', '/video/34 Sobredosis de Amor Los Titanes Salsa.mp4'),
(35, 35, 'Aparentemente', 'Tony Vega', 'Salsa', '/video/35 Tony Vega - Aparentemente.mp4'),
(36, 36, 'Esa Mujer', 'Tony Vega', 'Salsa', '/video/36 Tony Vega - Esa Mujer.mp4'),
(37, 37, 'Tu Eres Ajena', 'Eddy Herrera', 'Merengue', '/video/37 Tu eres ajena Eddy Herrera.mp4'),
(38, 38, 'Unicamente Tu', 'Felipe Pirela', 'Balada / Romántica', '/video/38 unicamente tu al estilo Felipe Pirela.mp4'),
(39, 39, 'Lastima Que Seas Ajena', 'Vicente Fernandez', 'Ranchera / Mariachi', '/video/39 vicente fernandez   lastima que seas ajena.mp4'),
(40, 40, 'Un Millon De Primaveras', 'Vicente Fernandez', 'Ranchera / Mariachi', '/video/40 Vicente Fernández   Un Millón De Primaveras.mp4'),
(41, 41, 'Esa Pared', 'Leo Dan', 'Balada / Romántica', '/video/41 Esa Pared - Leo Dan.mp4'),
(42, 42, 'Como Poder Saber Si Te Amo', 'Leo Dan', 'Balada / Romántica', '/video/42 Como poder saber si te amo - Leo Dan.mp4'),
(43, 43, 'Fuiste Mia Un Verano', 'Leonardo Favio', 'Balada / Romántica', '/video/43 FUISTE MÍA UN VERANO - LEONARDO FAVIO.mp4'),
(44, 44, 'Mary Es Mi Amor', 'Leo Dan', 'Balada / Romántica', '/video/44 LEO DAN MARY ES MI AMOR.mp4'),
(45, 45, 'Te He Prometido', 'Leo Dan', 'Balada / Romántica', '/video/45 Te he Prometido - Leo Dan.mp4'),
(46, 46, 'Angelito', 'Nacho', 'Pop Latino / Urbano', '/video/46 Angelito - Nacho  (2).mp4'),
(47, 47, 'Bailame', 'Nacho', 'Pop Latino / Urbano', '/video/47 Bailame - Nacho  (1).mp4'),
(48, 48, 'Hasta Que Te Conoci', 'Juan Gabriel', 'Balada / Romántica', '/video/48 HASTA QUE TE CONOCI    JUAN GABRIEL.mp4'),
(49, 49, 'Amores Como El Nuestro', 'Jerry Rivera', 'Salsa', '/video/49 Jerry Rivera - Amores Como El Nuestro.mp4'),
(50, 50, 'El Regalo Mas Grande', 'Tizziano Ferro', 'Variado / Éxitos', '/video/50 EL REGALO MAS GRANDE  TIZZIANO FERRO.mp4'),
(51, 51, 'Contigo En La Distancia', 'Luis Miguel', 'Variado / Éxitos', '/video/51_Luis_Miguel_-_Contigo_en_la_distancia_.mp4'),
(52, 52, 'Mi Vida Eres Tu', 'Rudy La Escala', 'Balada / Romántica', '/video/52-_Mi_vida_eres_tu_-rudy_la_ESCALA_.mp4'),
(53, 53, 'A Mi Manera', 'Frank Sinatra', 'Variado / Éxitos', '/video/53 A MI MANERA FRANK SINATRA.mp4'),
(54, 54, 'A Puro Dolor', 'Son By', 'Variado / Éxitos', '/video/54 A Puro Dolor (con letra) - Son by.mp4'),
(55, 55, 'Aguanile', 'Marck Antonhy', 'Variado / Éxitos', '/video/55 Aguanile  Marck Antonhy.mp4'),
(56, 56, 'Ahora Te Puedes Marchar', 'Luis Miguel', 'Variado / Éxitos', '/video/56 Ahora_Te_Puedes_Marchar_Luis_Miguel.mp4'),
(57, 57, 'Amarte Es Un Placer', 'Luis Miguel', 'Variado / Éxitos', '/video/57 Amarte_es_un_placer _LUIS_MIGUEL.mp4'),
(58, 58, 'Amor Verdadero', 'Willi Colon', 'Variado / Éxitos', '/video/58 Amor_verdadero-_Willie_Colon.mp4'),
(59, 59, 'Simplemente Amigos', 'Ana Gabriel', 'Balada / Romántica', '/video/59 Simplemente Amigos - Ana Gabriel.mov'),
(60, 60, 'Vivo Por Ella', 'Andrea Bochelli', 'Balada / Romántica', '/video/60 andrea bochelli - vivo por ella -.mpg'),
(61, 61, 'Apaga La Luz', 'Hildemaro', 'Salsa', '/video/61 Apago_La_Luz_-_Hildemaro_.mp4'),
(62, 62, 'Mi Mundo Tu', 'Camilo Sesto', 'Balada / Romántica', '/video/62 CAMILO_SESTO_MI_MUNDO_TU.mp4'),
(63, 63, 'Colgando En Tus Manos', 'Carlos Baute Y Martha Sanchez', 'Balada / Romántica', '/video/63 Carlos Baute y Martha Sanchez - Colgando en tus manos.mpg'),
(64, 64, 'Y Tu Te Vas', 'Chayanne', 'Pop Latino / Urbano', '/video/64 Chayanne - Y Tu Te Vas.mp4'),
(65, 65, 'Dejaria Todo', 'Chayanne', 'Pop Latino / Urbano', '/video/65 chayanne dejaria todo.mpg'),
(66, 66, 'El Hombre Que Yo Amo', 'Mirian Hernandez', 'Variado / Éxitos', '/video/66 El_hombre_que_yo_amo_Mirian_Hernandez.mp4'),
(67, 67, 'Ella Y El', 'Ricardo Arjona', 'Balada / Romántica', '/video/67 Ella Y El   Ricardo Arjona.mp4'),
(68, 68, 'Aquí Estas Otra Vez', 'Franco De Vita', 'Pop Latino / Urbano', '/video/68 Franco de Vita - Aqui Estas Otra Vez.mp4'),
(69, 69, 'Louis', 'Franco De Vita', 'Pop Latino / Urbano', '/video/69 Franco de Vita - Louis  Karaoke.mp4'),
(70, 70, 'No Hace Falta', 'Franco De Vita', 'Pop Latino / Urbano', '/video/70 Franco de Vita - No Hace Falta.mp4'),
(71, 71, 'No Hay Cielo', 'Franco De Vita', 'Pop Latino / Urbano', '/video/71 Franco de Vita - No Hay Cielo.mp4'),
(72, 72, 'Sera', 'Franco De Vita', 'Pop Latino / Urbano', '/video/72 Franco de Vita - Sera.mp4'),
(73, 73, 'Un Buen Perdedor', 'Franco De Vita', 'Pop Latino / Urbano', '/video/73 Franco de Vita - Un Buen Perdedor.mp4'),
(74, 74, 'Sin Poder Evitarlo', 'Frank Quintero', 'Balada / Romántica', '/video/74 Frank Quintero - Sin Poder Evitarlo.mp4'),
(75, 75, 'Todos Me Miran', 'Gloria Trevi', 'Variado / Éxitos', '/video/75 Gloria Trevi -Y Todos Me Miran.mp4'),
(76, 76, 'Barco A La Deriva', 'Guillermo Davila', 'Balada / Romántica', '/video/76 Guillermo Davila - Barco a la Deriva.mp4'),
(77, 77, 'Cantare Para Ti', 'Guillermo Davila', 'Balada / Romántica', '/video/77 Guillermo Davila - Cantare Para Ti Karaoke.mp4'),
(78, 78, 'Llevo Perfume A Ti', 'Guillermo Davila', 'Balada / Romántica', '/video/78 Guillermo Davila - Llevo Pefume a Ti Karaoke.mp4'),
(79, 79, 'Me Fascina', 'Guillermo Davila', 'Balada / Romántica', '/video/79 Guillermo Davila - Me Fascina Karaoke.mp4'),
(80, 80, 'Solo Pienso En Ti', 'Guillermo Davila', 'Balada / Romántica', '/video/80 Guillermo Davila - Solo Pienso en Ti Karaoke.mp4'),
(81, 81, 'No Me Ames', 'Marck Antonhy Y Jennifer Lopez', 'Variado / Éxitos', '/video/81 Jennifer Lopez y Mark Anthony - No me ames.3gp'),
(82, 82, 'El Cigarrillo', 'Ana Gabriel', 'Balada / Romántica', '/video/82 Ana Gabriel - El Cigarrillo.mp4'),
(83, 83, 'Ay Mujer', 'Juan Luis Guerra', 'Variado / Éxitos', '/video/83 Juan Luis Guerra - Ay Mujer Karaoke.mp4'),
(84, 84, 'Bachata Rosa', 'Juan Luis Guerra', 'Variado / Éxitos', '/video/84 Juan Luis Guerra - Bachata Rosa Karaoke.mp4'),
(85, 85, 'Burbujas De Amor', 'Juan Luis Guerra', 'Variado / Éxitos', '/video/85 Juan Luis Guerra - Burbujas de Amor Karaoke.mp4'),
(86, 86, 'Carta De Amor', 'Juan Luis Guerra', 'Variado / Éxitos', '/video/86 Juan Luis Guerra - Carta de Amor Karaoke.mp4'),
(87, 87, 'Bilirubina', 'Juan Luis Guerra', 'Variado / Éxitos', '/video/87 Juan Luis Guerra - La Bilirrubina Karaoke.mp4'),
(88, 88, 'Tu', 'Juan Luis Guerra', 'Variado / Éxitos', '/video/88 Juan Luis Guerra - Tu Karaoke.mp4'),
(89, 89, 'Visa Para Un Sueño', 'Juan Luis Guerra', 'Variado / Éxitos', '/video/89 Juan LUis Guerra - Visa Para un Sueño Karaoke.mp4'),
(90, 90, 'Llegaste Tu', 'Juan Luis Guerra Y Luis Fonsi', 'Pop Latino / Urbano', '/video/90 Juan Luis Guerra & Luis Fonsi - Llegaste Tu.mp4'),
(91, 91, 'Frio, Frio', 'Juan Luis Guerra Y Romeo Santos', 'Variado / Éxitos', '/video/91 Juan Luis Guerra & Romeo Santos -  Frio, Frio.mp4'),
(92, 92, 'Eres Todo En Mi', 'Ana Gabriel', 'Balada / Romántica', '/video/92 Ana Gabriel - Eres Todo En Mi.mp4'),
(93, 93, 'El Gran Varon', 'Willi Colon', 'Variado / Éxitos', '/video/93 Willie Colón - El gran varón.mp4'),
(94, 94, 'El Me Mintio', 'Amanda Miguel', 'Balada / Romántica', '/video/94  Amanda Miguel - El me mintió.mp4'),
(95, 95, 'Asi Fue', 'Juan Gabriel', 'Balada / Romántica', '/video/95  ASÍ FUE - al estilo de JUAN GABRIEL.mp4'),
(96, 96, 'Estoy Enamorado', 'Donato Y Stefano', 'Variado / Éxitos', '/video/96  ESTOY ENAMORADO (DONATO_STEFANO.mp4'),
(97, 97, 'Mi Abuela', 'Gualberto Ibarreto', 'Música Llanera', '/video/97 Gualberto Ibarreto - Mi Abuela.mp4'),
(98, 98, 'Historia De Un Taxi', 'Ricardo Arjona', 'Balada / Romántica', '/video/98 HISTORIA DE TAXI - al estilo de RICARDO ARJONA.mp4'),
(99, 99, 'Otra Como Tu', 'Eros Ramazotti', 'Balada / Romántica', '/video/99 OTRA COMO TÚ - al estilo de EROS RAMAZZOTTI.mp4'),
(100, 100, 'Que Sera De Ti', 'Thalia', 'Pop Latino / Urbano', '/video/100 QUÉ SERÁ DE TI - al estilo de ROBERTO CARLOS.mp4'),
(101, 101, 'Querida', 'Juan Gabriel', 'Balada / Romántica', '/video/101  QUERIDA - al estilo de JUAN GABRIEL.mp4'),
(102, 102, 'Se Me Olvido Otra Vez', 'Juan Gabriel', 'Balada / Romántica', '/video/102  SE ME OLVIDÓ OTRA VEZ - al estilo de JUAN GABRIEL.mp4'),
(103, 103, 'Siempre En Mi Mente', 'Juan Gabriel', 'Balada / Romántica', '/video/103  SIEMPRE EN MI MENTE - al estilo de JUAN GABRIEL.mp4'),
(104, 104, 'Tiempo De Vals', 'Chayanne', 'Pop Latino / Urbano', '/video/104 TIEMPO DE VALS - al estilo de CHAYANNE.mp4'),
(105, 105, 'Tusa', 'Karol G', 'Pop Latino / Urbano', '/video/105  (Tusa - Karol G_ Nicki Minaj).mp4'),
(106, 106, 'Fuiste Tu', 'Ricardo Arjona', 'Balada / Romántica', '/video/106 Fuiste Tu Ricardo Arjona(360P)_1.mp4'),
(107, 107, 'No Me Doy Por Vencido', 'Luis Fonsi', 'Pop Latino / Urbano', '/video/107 No me doy por vencido - Luis Fonsi _(480P)_1.mp4'),
(108, 108, 'Vivir Sin Aire', 'Mana', 'Rock / Pop-Rock', '/video/108 Vivir sin aire - Maná _(360P)_1.mp4'),
(109, 109, 'Hasta Que Me Olvides', 'Luis Miguel', 'Variado / Éxitos', '/video/109 hasta_que_me_olvides__luis_miguel.mp4'),
(110, 110, 'Amor A Millon', 'Karina', 'Variado / Éxitos', '/video/110 Karina_-_Amor_a_Milln(youtube.com).mp4'),
(111, 111, 'No Se Tu', 'Luis Miguel', 'Variado / Éxitos', '/video/111 No_se_t_-_Luis_Miguel(youtube.com).mp4'),
(112, 112, 'Melina', 'Camilo Sesto', 'Balada / Romántica', '/video/112 _CAMILO_SESTO__Melina(youtube.com).mp4'),
(113, 113, 'Hubo Alguien', 'Marck Antonhy', 'Variado / Éxitos', '/video/113 Hubo_alguien_Marc_Antony.mp4'),
(114, 114, 'Aquien', 'Karina', 'Variado / Éxitos', '/video/114 Karina_-_AQUIEN(youtube.com).mp4'),
(115, 115, 'Sabor A Mi', 'Luis Miguel', 'Variado / Éxitos', '/video/115 Sabor_A_Mi_-_Luis_Miguel_.mp4'),
(116, 116, 'Somos Novios', 'Luis Miguel', 'Variado / Éxitos', '/video/116 Somos_Novios_-_Luis_Miguel_(youtube.com).mp4'),
(117, 117, 'Gitana', 'Willi Colon', 'Salsa', '/video/117 WILLIE_COLON_GITANA_SALSA.mp4'),
(118, 118, 'Quieres Ser Mi Amante', 'Camilo Sesto', 'Balada / Romántica', '/video/118 quieres_ser_mi_amantecamilo_sesto.mp4'),
(119, 119, 'Se Como Duele', 'Karina', 'Variado / Éxitos', '/video/119 Karina - Sé como duele Karaoke.mp4'),
(120, 120, 'A Ella', 'Karol G', 'Pop Latino / Urbano', '/video/120 Karol G - A Ella [Karaoke](360P)_1.mp4'),
(121, 121, 'Malagueña', 'Varios', 'Variado / Éxitos', '/video/121 La Malagueña.mp4'),
(122, 122, 'Flor Palida', 'Marck Antonhy', 'Variado / Éxitos', '/video/122 Flor Palida - Marck Anthony.mp4'),
(123, 123, 'Mi Viejo', 'Piero', 'Variado / Éxitos', '/video/123 Mi viejo - Piero.mp4'),
(124, 124, 'Mujeres Divinas', 'Vicente Fernandez', 'Ranchera / Mariachi', '/video/124 Mujeres Divinas - Vicente Fernandez.mp4'),
(125, 125, 'Por Unas Monedas', 'Pepe Aguilar', 'Ranchera / Mariachi', '/video/125 Pepe Aguilar - Por Unas Monedas (Letra)(480P).mp4'),
(126, 126, 'Directo Al Corazon', 'Pepe Aguilar', 'Ranchera / Mariachi', '/video/126 Pepe Aguilar Directo Al Corazon Karaoke(480P).mp4'),
(127, 127, 'Como Yo', 'San Luis Y Silvestre', 'Vallenato', '/video/127 San Luis Ft. Silvestre Dangond - Como Yo Karaoke(360P)_1.mp4'),
(128, 128, 'Mientes Tan Bien', 'Sin Bandera', 'Pop Latino / Urbano', '/video/128 Sin Banderas Mientes Tan Bien.mp4'),
(129, 129, 'Si Tu No Estas Aquí', 'Sin Bandera', 'Pop Latino / Urbano', '/video/129 Sin Bandera - Si Tu No Estas Aqui (Versión Karaoke)(360P)_1.mp4'),
(130, 130, 'No Me Acuerdo', 'Thalia Y Natty Natacha', 'Pop Latino / Urbano', '/video/130 Thalía_ Natti Natasha - No Me Acuerdo - Karaoke(360P)_1.mp4'),
(131, 131, 'Y Volvere', 'Los Angeles Negros', 'Balada / Romántica', '/video/131 Y VOLVERE- LOS ANGELES NEGROS KARAOKE(360P)_1.mp4'),
(132, 132, 'Hechizo', 'Ana Gabriel', 'Balada / Romántica', '/video/132 Ana Gabriel - Hechizo.mp4'),
(133, 133, 'Luna', 'Ana Gabriel', 'Balada / Romántica', '/video/133 Ana Gabriel - Luna.mp4'),
(134, 134, 'Quien Como Tu', 'Ana Gabriel', 'Balada / Romántica', '/video/134 Ana Gabriel - Quien Como Tu.mp4'),
(135, 135, 'Mi Talisman', 'Ana Gabriel', 'Balada / Romántica', '/video/135 Ana Gabriel Mi Talisman.mp4'),
(136, 136, 'Esta Cobardia', 'Chiquetete', 'Variado / Éxitos', '/video/136 Chiquetete - Esta Cobardia.mp4'),
(137, 137, 'A Dios Le Pido', 'Juanes', 'Variado / Éxitos', '/video/137 Juanes - A Dios Le Pido.mp4'),
(138, 138, 'Que Sera De Ti.', 'Roberto Carlos', 'Balada / Romántica', '/video/138  Roberto Carlos - Que será de ti.mp4'),
(139, 139, 'Cosas Del Amor', 'Ana Gabriel', 'Balada / Romántica', '/video/139 COSAS DEL AMOR  ANA GABRIEL.mp4'),
(140, 140, 'Daria', 'La 5° Estacion', 'Balada / Romántica', '/video/140 La 5ª Estacion - Daria.mp4'),
(141, 141, 'El Sol No Regresa', 'La 5° Estacion', 'Balada / Romántica', '/video/141 La 5ª Estacion - El Sol No Regresa.mp4'),
(142, 142, 'Sueños Rotos', 'La 5° Estacion', 'Balada / Romántica', '/video/142 La 5ª Estacion - Sueños Rotos.mp4'),
(143, 143, 'Rosas', 'La Oreja De Van Gogh', 'Balada / Romántica', '/video/143 la oreja de van gogh -  rosas.mp4'),
(144, 144, 'Creo En Mi', 'Natalia Jimenez', 'Balada / Romántica', '/video/144 Natalia Jimenez - Creo En Mi.mp4'),
(145, 145, 'Como Olvidar', 'Olga Tañon', 'Merengue', '/video/145 Olga Tañon - Como Olvidar.mp4'),
(146, 146, 'Es Mentiroso', 'Olga Tañon', 'Merengue', '/video/146 Olga Tañon - Es Mentiroso.mp4'),
(147, 147, 'Flaca O Gordita', 'Olga Tañon', 'Merengue', '/video/147 Olga Tañon - Flaca O Gordita.mp4'),
(148, 148, 'La Loba', 'Las Chicas Del Can', 'Merengue', '/video/148 Yo no soy una loba _ Las Chicas del Can.mp4'),
(149, 149, 'Y Llegaste Tu', 'Sin Bandera', 'Pop Latino / Urbano', '/video/149 Sin Bandera - Y Llegaste Tu.mp4'),
(150, 150, 'La Negra Tiene Tumbao', 'Celia Cruz', 'Variado / Éxitos', '/video/150 Celia Cruz - La Negra Tiene Tumbao.mp4'),
(151, 151, 'Como La Flor', 'Selena', 'Cumbia / Tropical', '/video/151 Como la flor - Karaoke - Selena.mp4'),
(152, 152, 'Dejame Llorrar', 'Ricardo Montaner', 'Pop Latino / Urbano', '/video/152 Déjame Llorar - Ricardo Montaner(480P).mp4'),
(153, 153, 'Dicen Que El Primer Amor', 'Reinaldo Armas', 'Música Llanera', '/video/153 Dicen Que El Primer Amor   Reynaldo Armas.mp4'),
(154, 154, 'Me Falta Todo', 'Diveana', 'Merengue', '/video/154 Diveana - Me Falta Todo.mp4'),
(155, 155, 'Noches De Media Luna', 'Diveana', 'Merengue', '/video/155 DIVEANA NOCHES DE MEDIA LUNA.mp4'),
(156, 156, 'Que Locura Enamorarme De Ti', 'Eddy Santiago', 'Salsa', '/video/156 Eddie Santiago - Que Locura Enamorarme De Ti.mp4'),
(157, 157, 'Egoismo', 'Reinaldo Armas', 'Variado / Éxitos', '/video/157 Egoísmo.mp4'),
(158, 158, 'En Carne Viva', 'Varios', 'Variado / Éxitos', '/video/158 En Carne Viva.mp4'),
(159, 159, 'Deseandote', 'Frankie Ruiz', 'Salsa', '/video/159 Frankie Ruiz - Deseandote.mp4'),
(160, 160, 'Desnudate Mujer', 'Frankie Ruiz', 'Salsa', '/video/160 Frankie Ruiz - Desnúdate Mujer.mp4'),
(161, 161, 'Mi Buen Amor', 'Gloria Estefan', 'Variado / Éxitos', '/video/161 Gloria Estefan - Mi Buen Amor.mp4'),
(162, 162, 'El Cantante', 'Hector Lavoe', 'Salsa', '/video/162 Hector Lavoe - El Cantante.mp4'),
(163, 163, 'Como Tu Mujer', 'Rocio Durcal', 'Balada / Romántica', '/video/163  Rocío Dúrcal - Cómo tu mujer -.mp4'),
(164, 164, 'Quisiera Ser', 'Luis Silva', 'Música Llanera', '/video/164 Quisiera ser - Luis Silva - LLANERA.mp4'),
(165, 165, 'Amanecer', 'Diveana', 'Merengue', '/video/165  Amanecer Diveana(720P_HD).mp4'),
(166, 166, 'Como No Voy A Decir', 'Luis Silva', 'Música Llanera', '/video/166  Como no voy a decir(480P).mp4'),
(167, 167, 'Talento De Television', 'Willi Colon', 'Variado / Éxitos', '/video/167 Talento de Television - Willi Colon.mp4'),
(168, 168, 'Que Hay De Malo', 'Jerry Rivera', 'Salsa', '/video/168 QUE HAY DE MALO JERRY RIVERA.mp4'),
(169, 169, 'Una Casita Bella', 'Cristobal Jimenez', 'Música Llanera', '/video/169 _Una casita bella_ Cristóbal Jiménez(720P_HD).mp4'),
(170, 170, 'Lo Que Yo Se', 'Diveana', 'Merengue', '/video/170  lo que yo se   diveana.mp4'),
(171, 171, 'Bandolero', 'Olga Tañon', 'Merengue', '/video/171 Olga Tañón - Bandolero(480P).mp4'),
(172, 172, 'Tus Ojos', 'Diveana', 'Merengue', '/video/172 Tus ojos (Original)  Diveana(480P).mp4'),
(173, 173, 'Ese Hombre', 'La India', 'Variado / Éxitos', '/video/173 La India - Ese Hombre.mp4'),
(174, 174, 'La Muerte Del Rucio Moro', 'Reinaldo Armas', 'Variado / Éxitos', '/video/174 La Muerte del Rucio Moro.mp4'),
(175, 175, 'La Viuda Millonaria', 'Santiago Rojas', 'Variado / Éxitos', '/video/175 La Viuda Millonaria (Karaoke)(480P).mp4'),
(176, 176, 'Huele A Peligro', 'Mirian Hernandez', 'Balada / Romántica', '/video/176 Myriam Hernandez - Huele A Peligro.mp4'),
(177, 177, 'Y Siempre', 'Karolina Con K', 'Merengue', '/video/177 Y siempre Karolina con K.mp4'),
(178, 178, 'Muchacho Malo', 'Olga Tañon', 'Merengue', '/video/178 Olga Tañon - Muchacho Malo.mp4'),
(179, 179, 'Presencie Tu Amor', 'Olga Tañon', 'Merengue', '/video/179 Olga Tañon - Presencie Tu Amor.mp4'),
(180, 180, 'Se Que Vendras Llorando', 'Olga Tañon', 'Merengue', '/video/180 Olga Tañon - Se Que Vendras Llorando.mp4'),
(181, 181, 'Mujeres', 'Ricardo Arjona', 'Balada / Romántica', '/video/181 Ricardo Arjona - Mujeres.mp4'),
(182, 182, 'Amor Prohibido', 'Selena', 'Cumbia / Tropical', '/video/182 Selena - Amor Prohibido.mp4'),
(183, 183, 'Ciega Sordomuda', 'Shakira', 'Pop Latino / Urbano', '/video/183 Shakira - Ciega Sordomuda.mp4'),
(184, 184, 'Si Una Vez', 'Selena', 'Cumbia / Tropical', '/video/184 Si una vez - Selena Quintanilla.mp4'),
(185, 185, 'Aqi Estoy Yo', 'Luis Fonsi', 'Pop Latino / Urbano', '/video/185 Aqui Estoy Yo_ con letra - Luis Fonsi.mp4'),
(186, 186, 'Alejate De Mi', 'Camila', 'Pop Latino / Urbano', '/video/186 Camila   Alejate De Mi.mp4'),
(187, 187, 'Carrao Carrao', 'Reyna Lucero', 'Música Llanera', '/video/187 Carrao_ Carrao.mp4'),
(188, 188, 'Atado A Tu Amor', 'Chayanne', 'Pop Latino / Urbano', '/video/188 Chayanne  Atado A Tu Amor.mp4'),
(189, 189, 'Yo Te Amo', 'Chayanne', 'Pop Latino / Urbano', '/video/189 Chayanne  Yo Te Amo.mp4'),
(190, 190, 'Tu Angelito', 'Chino Y Nacho', 'Pop Latino / Urbano', '/video/190 Chino _ Nacho - Tu Angelito.mp4'),
(191, 191, 'Te Quiero Mas', 'Tini Y Nacho', 'Pop Latino / Urbano', '/video/191 TINI_ Nacho - Te Quiero Más.mp4'),
(192, 192, 'Despacito', 'Luis Fonsi', 'Pop Latino / Urbano', '/video/192 Despacito - Luis Fonsi ft Daddy Yankee.mp4'),
(193, 193, 'Color Esperanza', 'Diego Torres', 'Balada / Romántica', '/video/193 Diego Torres - Color Esperanza -.mp4'),
(194, 194, 'Guitarra Española', 'Diveana', 'Merengue', '/video/194 Diveana   Mix Soy Castellana Guitarra Espanola.mp4'),
(195, 195, 'El Rey', 'Vicente Fernandez', 'Ranchera / Mariachi', '/video/195 El Rey  Al Estilo De Vicente Fernández.mp4'),
(196, 196, 'Si La Ves', 'Franco De Vita', 'Pop Latino / Urbano', '/video/196 Franco De Vita _ Sin Bandera - Si La Ves.mp4'),
(197, 197, 'Conciencia', 'Gilberto Santa Rosa', 'Salsa', '/video/197 Gilberto Santa Rosa - Conciencia.mp4'),
(198, 198, 'Sombras', 'Javier Solis', 'Ranchera / Mariachi', '/video/198 Javier Solis   Sombras.mp4'),
(199, 199, 'Que Pasara Mañana', 'Jose Luis Perales', 'Balada / Romántica', '/video/199 Jose Luis Perales - Que Pasara Mañana.mp4'),
(200, 200, 'Abrazame Muy Fuerte', 'Juan Gabriel', 'Balada / Romántica', '/video/200 Juan Gabriel - Abrazame Muy Fuerte.mp4'),
(201, 201, 'A Quien No Le Va A Gusta', 'Cheo Hernandez', 'Música Llanera', '/video/201 A quien no le va a gustar_ folklore llanero.mp4'),
(202, 202, 'Frio Frio', 'Juan Luis Guerra', 'Variado / Éxitos', '/video/202 Juan Luis Guerra & Romeo Santos -  Frio, Frio.mp4'),
(203, 203, 'Ella', 'Julio Miranda', 'Variado / Éxitos', '/video/203 Julio Miranda   Ella.mp4'),
(204, 204, 'Piel De Angel', 'Camilo Sesto', 'Balada / Romántica', '/video/204  Camilo Sesto - Piel de ángel.mp4'),
(205, 205, 'Flor Sin Retoño', 'Pedro Infante', 'Ranchera / Mariachi', '/video/205 Pedro Infante - Flor sin retoño.mp4'),
(206, 206, 'Entra En Mi Vida', 'Sin Bandera', 'Pop Latino / Urbano', '/video/206  Sin Bandera - Entra en mi vida.mp4'),
(207, 207, 'Mi Eterno Amor Secreto', 'Marco Antonio Solis', 'Balada / Romántica', '/video/207 MI ETERNO AMOR SECRETO - MARCO ANTONIO SOLÍS.mp4'),
(208, 208, 'Ay Amor', 'Melodicos', 'Merengue', '/video/208  AY AMOR (MELODICOS).mp4'),
(209, 209, 'De Que Me Sirve La Vida', 'Camila', 'Pop Latino / Urbano', '/video/209  De Qué Me Sirve La Vida   Camila avi.mp4'),
(210, 210, 'Dos Mujeres En Mi Vida', 'Teo Galindez', 'Música Llanera', '/video/210  Dos Mujeres en mi Vida - Teo Galindez.mp4'),
(211, 211, 'Homenaje A Pastor Lopez', 'Pollo Brito', 'Cumbia / Tropical', '/video/211 homenaje a pastor lopez free cover venezuela ft pollo brito.mp4'),
(212, 212, 'Esclavo Y Amo', 'Javier Solis', 'Ranchera / Mariachi', '/video/212  Javier Solis - Esclavo y amo.mp4'),
(213, 213, 'Mi Niña Bonita', 'Chino Y Nacho', 'Pop Latino / Urbano', '/video/213 Mi Niña Bonita - Chino _ Nacho.mp4'),
(214, 214, 'Si No Te Hubieras Ido', 'Marco Antonio Solis', 'Balada / Romántica', '/video/214 Si No Te Hubieras Ido   Marco Antonio Solis.mp4'),
(215, 215, 'No Me Corra Cantinero', 'Vitico Castillo', 'Música Llanera', '/video/215 Vitico Castillo No me corra cantinero.mp4'),
(216, 216, 'Salvame', 'Karina', 'Variado / Éxitos', '/video/216 KARINA SALVAME.mp4'),
(217, 217, 'La Media Vuelta', 'Javier Solis', 'Ranchera / Mariachi', '/video/217 La Media Vuelta  Javier Solis.mp4'),
(218, 218, 'La Potra Zaina', 'Varios', 'Variado / Éxitos', '/video/218 LA POTRA ZAINA.mp4'),
(219, 219, 'Laguna Vieja', 'Rummy Olivo', 'Música Llanera', '/video/219 Laguna Vieja - Rummy Olivo.mp4'),
(220, 220, 'Laguna Vieja', 'Reinaldo Armas', 'Música Llanera', '/video/220 Laguna Vieja (Tono Original) - Reynaldo Armas.mp4'),
(221, 221, 'O Quizas Simplemente Le Regale Una Rosa', 'Leonardo Favio', 'Balada / Romántica', '/video/221 Leonardo Favio O quizás simplemente le regale una rosa.mp4'),
(222, 222, 'Si Tu Me Dices Ven', 'Los Panchos', 'Balada / Romántica', '/video/222 Los Panchos - Si Tu Me Dices Ven.mp4'),
(223, 223, 'Sin Ti', 'Los Panchos', 'Balada / Romántica', '/video/223 Los Panchos - Sin Ti.mp4'),
(224, 224, 'Imaginame Sin Ti', 'Luis Fonsi', 'Pop Latino / Urbano', '/video/224 Luis Fonsi - Imaginame Sin Ti.mp4'),
(225, 225, 'A Tu Medida', 'Karolina Con K', 'Merengue', '/video/225 A Tú Medida   Karolina.mp4'),
(226, 226, 'Mariposa Traicionera', 'Mana', 'Rock / Pop-Rock', '/video/226 Mana - Mariposa Traicionera -.mp4'),
(227, 227, 'Me Dedique A Perderte', 'Alejandro Fernandez', 'Variado / Éxitos', '/video/227 Me Dedique a Perderte   Alejandro Fernandez.mp4'),
(228, 228, 'Me Duele Amarte', 'Reik', 'Pop Latino / Urbano', '/video/228 Me Duele Amarte - Reik.mp4'),
(229, 229, 'Aunque Me Cueste La Vida', 'Sonora Matansera', 'Cumbia / Tropical', '/video/229 Auenque me cueste la vida - Sonora Matancera.mp4'),
(230, 230, 'Contigo O Sin Ti', 'Olga Tañon', 'Merengue', '/video/230 Olga Tañon - Contigo O Sin Ti.mp4'),
(231, 231, 'El Ultimo Adios', 'Paulina Rubio', 'Pop Latino / Urbano', '/video/231 Paulina Rubio    El ultimo adios.mp4'),
(232, 232, 'Amiga', 'Rey Ruiz', 'Salsa', '/video/232 Amiga - ReyRuiz.mp4'),
(233, 233, 'Como Podre Disimular', 'Grupo Niche', 'Salsa', '/video/233 Cómo Podré Disimular_  Grupo Niche.mp4'),
(234, 234, 'Dejate Querrer', 'Palinio Hernandez', 'Variado / Éxitos', '/video/234 Déjate Querer.mp4'),
(235, 235, 'Ella O El', 'Luis Silva', 'Música Llanera', '/video/235 Ella o El Luis Silva.mp4'),
(236, 236, 'Nuestra Cancion', 'Elvis Crespo', 'Variado / Éxitos', '/video/236 Elvis Crespo - Nuestra Cancion.mp4'),
(237, 237, 'Tu Sonrisa', 'Elvis Crespo', 'Variado / Éxitos', '/video/237 Elvis Crespo - Tu Sonrisa.mp4'),
(238, 238, 'Coleccionista De Canciones', 'Camila', 'Pop Latino / Urbano', '/video/238 Camila - Coleccionista De Canciones.mp4'),
(239, 239, 'Calido Y Frio', 'Franco De Vita', 'Pop Latino / Urbano', '/video/239 Franco De Vita - Calido Y Frio.mp4'),
(240, 240, 'Y Te Pienso', 'Franco De Vita', 'Pop Latino / Urbano', '/video/240 Franco De Vita - Y Te Pienso.mp4'),
(241, 241, 'Lo Dudo', 'Frankie Ruiz', 'Salsa', '/video/241 Frankie Ruiz   Lo Dudo _.mp4'),
(242, 242, 'Linda He', 'Grupo Mania', 'Merengue', '/video/242 Grupo Mania - Linda Eh.mp4'),
(243, 243, 'Hagamos Lo Que Diga El Corazon', 'Grupo Niche', 'Salsa', '/video/243 Hagamos lo que diga el corazón - (salsa) grupo Niche.mp4'),
(244, 244, 'El Triste', 'Jose Jose', 'Balada / Romántica', '/video/244 Jose Jose - El triste.mp4'),
(245, 245, 'Amor Eterno', 'Rocio Durcal', 'Balada / Romántica', '/video/245  Rocío Dúrcal - Amor eterno.mp4'),
(246, 246, 'Fue Un Placer Conocerte', 'Rocio Durcal', 'Balada / Romántica', '/video/246  Rocío Dúrcal - Fue un placer conocerte.mp4'),
(247, 247, 'Jamas Te Dejare', 'Rocio Durcal', 'Balada / Romántica', '/video/247 Rocío Dúrcal - Jamás te dejaré.mp4'),
(248, 248, 'No Crezcas Mas', 'Tercer Cielo', 'Balada / Romántica', '/video/248  Tercer Cielo - No crezcas más.mp4'),
(249, 249, 'No Basta', 'Franco De Vita', 'Pop Latino / Urbano', '/video/249 Franco De Vita - No basta.mp4'),
(250, 250, 'Homenaje A Selena', 'Free Cover', 'Cumbia / Tropical', '/video/250 homenaje a selena quintanilla   free cover.mp4'),
(251, 251, 'La Gran Fiesta', 'Olga Tañon', 'Merengue', '/video/251  LA GRAN FIESTA OLGA TAÑON.mp4'),
(252, 252, 'Mix Merengue Femenino', 'Femenino', 'Merengue', '/video/252 mix merengue femenino.mp4'),
(253, 253, 'Mix Victor Muñoz', 'Free Cover', 'Variado / Éxitos', '/video/253  mix victor muñoz  free cover(.mp4'),
(254, 254, 'No Te Tengo A Ti', 'Oscarcito', 'Balada / Romántica', '/video/254  no te tengo a ti (live) oscarcito ft ronald_ servando victor muñoz y yasmil marrufo.mp4'),
(255, 255, 'Si Quieres Mi Amor', 'Karolina Con K', 'Merengue', '/video/255 SI QUIERES MI AMOR - KAROLINA CON K.mp4'),
(256, 256, 'Solo Contigo', 'Omar Acedo', 'Balada / Romántica', '/video/256  solo contigo con coros    omar acedo.mp4'),
(257, 257, 'Yo Te Extrañare', 'Tercer Cielo', 'Balada / Romántica', '/video/257  yo te extrañare Con coros   Tercer cielo.mp4'),
(258, 258, 'La Quiero A Morir', 'Sergio Vargas', 'Merengue', '/video/258 La quiero a morir Sergio Vargas.mp4'),
(259, 259, 'Lloraras', 'Oscar De Leon', 'Salsa', '/video/259 Lloraras - Oscar de León.mp4'),
(260, 260, 'Mi Mundo Es De Ella', 'Maelo Ruiz', 'Salsa', '/video/260 Maelo Ruiz - Mi Mundo Es De Ella.mp4'),
(261, 261, 'Mentiritas', 'Karolina Con K', 'Merengue', '/video/261 Mentiritas _ Karolina.mp4'),
(262, 262, 'Mi Ultimo Dia', 'Tercer Cielo', 'Balada / Romántica', '/video/262 Mi ultimo dia - Tercer Cielo.mp4'),
(263, 263, 'Nada Sin Ti', 'Jerry Rivera', 'Salsa', '/video/263 Nada sin ti - Jerry Rivera.mp4'),
(264, 264, 'Noches Vacias', 'Karolina Con K', 'Merengue', '/video/264 Noches vacias Karolina con K.mp4'),
(265, 265, 'Nuestro Sueño', 'Grupo Niche', 'Salsa', '/video/265 Nuestro Sueño_  Grupo Niche.mp4'),
(266, 266, 'Vivo La Vida', 'Olga Tañon', 'Merengue', '/video/266 Olga Tañon -  Vivo La Vida -.mp4'),
(267, 267, 'Mi Media Mitad', 'Rey Ruiz', 'Salsa', '/video/267 Rey Ruiz - Mi Media Mitad.mp4'),
(268, 268, 'No Me Acostumbro', 'Rey Ruiz', 'Salsa', '/video/268 Rey Ruiz - No Me Acostumbro.mp4'),
(269, 269, 'Vuelve', 'Ricky Martin', 'Variado / Éxitos', '/video/269 Ricky Martin - Vuelve.mp4'),
(270, 270, 'Sombras', 'Rocio Durcal', 'Balada / Romántica', '/video/270 Rocio Durcal - Sombras.mp4'),
(271, 271, 'Homenaje A Sexagesimo', 'Rogelio Ortiz', 'Variado / Éxitos', '/video/271 Rogelio Ortíz - Homenaje a Sexagésimo.mp4'),
(272, 272, 'Sera Que Si', 'Maelo Ruiz', 'Salsa', '/video/272 Será Que Si_ Maelo Ruiz -.mp4'),
(273, 273, 'Caballo Viejo', 'Simon Diaz', 'Música Llanera', '/video/273 Simon Diaz - Caballo Viejo.mp4'),
(274, 274, 'Sin Sentimiento', 'Grupo Niche', 'Salsa', '/video/274 Sin Sentimiento_  Grupo Niche.mp4'),
(275, 275, 'Te Va A Doler', 'Maelo Ruiz', 'Salsa', '/video/275 Te Va A Doler_ Maelo Ruiz.mp4'),
(276, 276, 'Ella Se Hizo Deseo', 'Tito Rojas', 'Salsa', '/video/276 TITO ROJAS - ELLA SE HIZO DESEO.mp4'),
(277, 277, 'Una Mina De Amor', 'Ignacio Rondon', 'Música Llanera', '/video/277 Una mina de amor Ignacio Rondon.mp4'),
(278, 278, 'Siempre Sere', 'Tito Rojas', 'Salsa', '/video/278 Tito Rojas - Siempre Sere.mp4'),
(279, 279, 'Un Buen Perdedor', 'Franco De Vita', 'Pop Latino / Urbano', '/video/279 Un Buen Perdedor.mp4'),
(280, 280, 'Una Vaina Loca', 'Fuego', 'Cumbia / Tropical', '/video/280 (Una Vaina Loca - Fuego)(720P_HD).mp4'),
(281, 281, 'De Los Besos Que Te Di', 'Cristian Nodal', 'Ranchera / Mariachi', '/video/281 DE LOS BESOS QUE TE DI - CRISTIAN NODAL.mp4'),
(282, 282, 'Mix Salsa', 'Free Cover Los Pinkis', 'Salsa', '/video/282 mix salsa fre cover exitos de salsa erotica los pikis.mp4'),
(283, 283, 'Mix Merengue Masculino', 'Bailables', 'Merengue', '/video/283  MIX MERENGUE BAILABLE.mp4'),
(284, 284, 'Un Hombre Busca Una Mujer', 'Jossie Esteban', 'Merengue', '/video/284 Un hombre busca una mujer Jossie Esteban y La Patrulla 15.mp4'),
(285, 285, 'Bidi Bidi Bom Bom', 'Selena', 'Cumbia / Tropical', '/video/285  Bidi Bidi Bom Bom -  Selena.mp4'),
(286, 286, 'Perdoname', 'Gilberto Santa Rosa', 'Salsa', '/video/286 Gilberto Santa Rosa - Perdoname.mp4'),
(287, 287, 'Es Diferente', 'Jose Gregorio Oquendo', 'Música Llanera', '/video/287 Es Diferente - llanera.mp4'),
(288, 288, 'Tu Carcel', 'Los Bukis', 'Balada / Romántica', '/video/288 Tu Carcel - Los Bukis.mp4'),
(289, 289, 'El Amor Mas Bonito', 'Tito Nieves', 'Salsa', '/video/289 El Amor mas Bonito - Tito Nieves.mp4'),
(290, 290, 'Fabricando Fantasias', 'Tito Nieves', 'Salsa', '/video/290 Fabricando Fantasias - Tito Nieves.mp4'),
(291, 291, 'Mas Que Tu Amigo', 'Tito Nieves', 'Salsa', '/video/291 Tito Nieves - Mas Que Tu Amigo.mp4'),
(292, 292, 'La Ley Del Monte', 'Vicente Fernandez', 'Ranchera / Mariachi', '/video/292 La Ley Del Monte  - Fue Éxito De Vicente Fernández(.mp4'),
(293, 293, 'La Derrota', 'Vicente Fernandez', 'Ranchera / Mariachi', '/video/293 La Derrota -  Vicente Fernández.mp4'),
(294, 294, 'Por Tu Maldito Amor', 'Vicente Fernandez', 'Ranchera / Mariachi', '/video/294 Vicente Fernandez - Por Tu Maldito Amor.mp4'),
(295, 295, 'Niña Hechicera', 'Vicente Fernandez', 'Ranchera / Mariachi', '/video/295 Vicente Fernandez - Niña Hechicera.mp4'),
(296, 296, 'Una Fotografia', 'Bonny Cepeda', 'Merengue', '/video/296 UNA FOTOGRAFIA BONNY CEPEDA (MERENGUE).mp4'),
(297, 297, 'Ni Tu Ni Yo', 'Sergio Vargas', 'Merengue', '/video/297 Sergio Vargas - Ni Tu Ni Yo.mp4'),
(298, 298, 'Padre E Hijo', 'Oscar De Leon', 'Salsa', '/video/298 Oscar D_ Leon Padre E Hijo.mp4'),
(299, 299, 'Si Algun Dia La Ves', 'Sergio Vargas', 'Merengue', '/video/299 SERGIO VARGAS   SI ALGUN DIA LA VES.mp4'),
(300, 300, 'Que Siga Amandote', 'Carlos Alfredo', 'Variado / Éxitos', '/video/300 Que Siga Amándote - Carlos Alfredo.mp4'),
(301, 301, 'La Cadena Del Chisme', 'Edgardo Ramirez', 'Variado / Éxitos', '/video/301  La Cadena del Chisme.mp4'),
(302, 302, 'Aca Entre Nos', 'Vicente Fernandez', 'Ranchera / Mariachi', '/video/302 Vicente Fernandez - Aca Entre Nos.mp4'),
(303, 303, 'El Jardinero', 'Wilfrido Vargas', 'Merengue', '/video/303 El Jardinero Wilfrido Vargas.mp4'),
(304, 304, 'El Cantinero', 'Jossie Esteban', 'Merengue', '/video/304 JOSSIE ESTEBAN - EL CANTINERO.mp4'),
(305, 305, 'El Tigueron', 'Jossie Esteban', 'Merengue', '/video/305 JOSSIE ESTEBAN - EL TIGUERON.mp4'),
(306, 306, 'Noches De Fantasias', 'Josehp Fonseca', 'Merengue', '/video/306 Noches de Fantasia - Joseph Fonseca.mp4'),
(307, 307, 'Estos Celos', 'Vicente Fernandez', 'Ranchera / Mariachi', '/video/307 Estos Celos - Vicente Fernandez.mp4'),
(308, 308, 'Recuerdo De Una Noche', 'Los Pasteles Verdes', 'Balada / Romántica', '/video/308 Los Pasteles Verdes - Recuerdo de una noche.mp4'),
(309, 309, 'Te Juro Que Te Amo', 'Los Terricolas', 'Balada / Romántica', '/video/309 Los Terricolas - Te juro que te amo.mp4'),
(310, 310, 'El Idiota', 'Eddy Herrera', 'Merengue', '/video/310 El idiota _ Eddy Herrera.mp4'),
(311, 311, 'Como Quisiera Decirte', 'Los Angeles Negros', 'Balada / Romántica', '/video/311  Los Ángeles Negros - Cómo quisiera decirte.mp4'),
(312, 312, 'Que Cara Mas Bonita', 'Alex Bueno', 'Variado / Éxitos', '/video/312  Que cara mas bonita Alex Bueno(360P).mp4'),
(313, 313, 'Lamento Boliviano', 'Los Enanitos Verdes', 'Rock / Pop-Rock', '/video/313 Los Enanitos Verdes - Lamento Boliviano.mp4'),
(314, 314, 'Esclavo Y Amo', 'Los Pasteles Verdes', 'Balada / Romántica', '/video/314 Los Pasteles Verdes - Esclavo y Amo.mp4'),
(315, 315, 'Lloraras Terricolas', 'Los Terricolas', 'Balada / Romántica', '/video/315 LOS TERRICOLAS - LLORARAS.mp4'),
(316, 316, 'Pegame Tu Vicio', 'Eddy Herrera', 'Merengue', '/video/316 Pegame tu vicio Eddy Herrera.mp4'),
(317, 317, 'Tomate Una Copa', 'Javier Solis', 'Ranchera / Mariachi', '/video/317 Tomate Una Copa   JAVIER SOLIS.mp4'),
(318, 318, 'Amor Por Ti', 'German De La Fuente', 'Variado / Éxitos', '/video/318 Amor por ti.mp4'),
(319, 319, 'Claro', 'Tito Rojas', 'Salsa', '/video/319 Claro.mp4'),
(320, 320, 'Como Deseo Ser Tu Amor', 'Elio Roca', 'Variado / Éxitos', '/video/320 Comó deseo ser tu amor - Elio Roca.mp4'),
(321, 321, 'Deseandote .', 'Varios', 'Variado / Éxitos', '/video/321 Deseandote.mp4'),
(322, 322, 'Detalles', 'Oscar De Leon', 'Salsa', '/video/322 Detalles Oscar de Leon.mp4'),
(323, 323, 'Dime Como Llego A Ti', 'Erick Franchesky', 'Variado / Éxitos', '/video/323 Erick Franchesky Dime Como Llego A Ti.mp4'),
(324, 324, 'Buenos Dias Tristeza', 'Isabel Pantoja', 'Balada / Romántica', '/video/324 Isabel Pantoja - Buenos Dias Tristeza.mp4'),
(325, 325, 'Hasme Tuya Una Vez Mas', 'Isabel Pantoja', 'Balada / Romántica', '/video/325 Isabel Pantoja - Hazme Tuya Una Vez Mas.mp4'),
(326, 326, 'Hoy Quiero Confesarme', 'Isabel Pantoja', 'Balada / Romántica', '/video/326 Isabel Pantoja - Hoy Quiero Confesarme.mp4'),
(327, 327, 'Marinero De Luces', 'Isabel Pantoja', 'Balada / Romántica', '/video/327 Isabel Pantoja - Marinero De Luces.mp4'),
(328, 328, 'Dime Porque', 'Ismael Rivera', 'Salsa', '/video/328 Ismael_Rivera___Dime_Porque.mp4'),
(329, 329, 'Soy Feliz', 'Ismael Rivera', 'Salsa', '/video/329 Ismael_Rivera_Soy_Feliz_Karaoke.mp4'),
(330, 330, 'Rebelion', 'Joe Arroyo', 'Salsa', '/video/330 Joe Arroyo - Rebelión.mp4'),
(331, 331, 'Mi Gloria Es Tu Condena', 'Liz', 'Balada / Romántica', '/video/331  Liz   mi gloria es tu condena.mp4'),
(332, 332, 'Enfurecida', 'Luis Silva', 'Música Llanera', '/video/332 ENFURECIDA - LUIS SILVA.mp4'),
(333, 333, 'Para Toda La Vida', 'Teo Galindez', 'Música Llanera', '/video/333  Para Todita la Vida - Teo Galindez.mp4'),
(334, 334, 'Idilio', 'Willi Colon', 'Variado / Éxitos', '/video/334 Willie_Colon_Idilio.mp4'),
(335, 335, 'La Hija De Nadie', 'Yolanda Del Rio', 'Variado / Éxitos', '/video/335 Yolanda Del Rio - La Hija De Nadie.mp4'),
(336, 336, 'Señora', 'Rocio Durcal', 'Balada / Romántica', '/video/336 Rocio Jurado - Señora.mp4'),
(337, 337, 'Medias Negras', 'Willi Chirinos', 'Variado / Éxitos', '/video/337 MEDIAS_NEGRAS__Willy_Chirino.mp4'),
(338, 338, 'Si Me Ves Llorar Por Ti', 'David Pabon', 'Variado / Éxitos', '/video/338 Si me ves llorar por ti - David Pavon.mp4'),
(339, 339, 'Hasta El Sol De Hoy', 'Edgar Joel', 'Variado / Éxitos', '/video/339 Hasta el Sol de hoy - Edgar Joel.mp4'),
(340, 340, 'Un Lobo Domesticado', 'Tommy', 'Variado / Éxitos', '/video/340 Un lobo Domesticado - Tommy.mp4'),
(341, 341, 'Mi Libertad', 'Frankie Ruiz', 'Salsa', '/video/341 Mi Libertad - Frankie Ruiz.mp4'),
(342, 342, 'Ella Es', 'Tony Vega', 'Salsa', '/video/342 Ella es - Tonny Vega.mp4'),
(343, 343, 'A Pesar De Todo', 'Vicente Fernandez', 'Ranchera / Mariachi', '/video/343 Vicente Fernandez - A Pesar De Todo.mp4'),
(344, 344, 'En Mi Viejo San Juan', 'Trio Vergolaña', 'Balada / Romántica', '/video/344 Trio Vegabajeño - En Mi Viejo San Juan.mp4'),
(345, 345, 'Mi Desengaño', 'Roberto Roena', 'Salsa', '/video/345  MI DESENGAÑO ROBERTO ROENA.mp4'),
(346, 346, 'Tengo Derecho A Ser Feliz', 'Junior Gonzalez', 'Salsa', '/video/346  Junior Gonzelez  tengo derecho a ser feliz salsa.mp4'),
(347, 347, 'Ole Con Ole', 'Los Master', 'Variado / Éxitos', '/video/347 Olo con Ole - los Master.mp4'),
(348, 348, 'Sueños De Pescador', 'Los Master', 'Variado / Éxitos', '/video/348 Sueños de Pescador - Los Master.mp4'),
(349, 349, 'Autopista Desierta', 'Salsa', 'Salsa', '/video/349 Autopista desierta - Salsa.mp4'),
(350, 350, 'Ay Amor Cuando Hablan Las Miradas', 'Salsa', 'Salsa', '/video/350 Ay Amor cuando hablan las miradas - Salsa.mp4'),
(351, 351, 'Como Te Hago Entender', 'Roberto Roena', 'Salsa', '/video/351 Como te hago entender - Roberto Roena.mp4'),
(352, 352, 'Un Millon De Estrellas', 'Polo Montañez', 'Balada / Romántica', '/video/352 Un monton de Estrellas - Polo Montañez.mp4'),
(353, 353, 'Tu Voz', 'Javier Solis', 'Ranchera / Mariachi', '/video/353 Javier Solís - Tu voz.mp4'),
(354, 354, 'Aquel', 'Simon Diaz', 'Música Llanera', '/video/354 AQUEL - SIMON DIAZ.mp4'),
(355, 355, 'Corazon De Concreto', 'Vitico Castillo', 'Música Llanera', '/video/355  Vitico Castillo _Corazón de concreto.mp4'),
(356, 356, 'Para Todita La Vida', 'Teo Galindez', 'Música Llanera', '/video/356 Para Todita la Vida - Teo Galindez.mp4'),
(357, 357, 'Por Ella', 'Carruyo', 'Variado / Éxitos', '/video/357  POR ELLA_ CARRUYO.mp4'),
(358, 358, 'Loco', 'Alejandro Fernandez', 'Variado / Éxitos', '/video/358 Alejandro Fernandez - Loco.mp4'),
(359, 359, 'Cuando Yo Queria Ser Grande', 'Vicente Fernandez', 'Ranchera / Mariachi', '/video/359 cuando yo queria ser grande.mp4'),
(360, 360, 'Holocausto De Amor', 'Pedro Luis Gomez', 'Variado / Éxitos', '/video/360 Holocausto de Amor.mp4'),
(361, 361, 'Lo Siento Mi Amor', 'Raul Gallimore', 'Variado / Éxitos', '/video/361 Lo siento mi Amor - Raul Gallimore.mp4'),
(362, 362, 'Quiero Decirte', 'Sebastian Yatra', 'Pop Latino / Urbano', '/video/362 Quiero Decirte - Sebastian Yatra.mp4'),
(363, 363, 'Preguntale Al Destino', 'Greiccy Y Nacho', 'Pop Latino / Urbano', '/video/363 Preguntale al Destino - Greiccy y Nacho.mp4'),
(364, 364, 'Lagrimas', 'Roberto Blades', 'Salsa', '/video/364 Lagrimas - Roberto Blades.mp4'),
(365, 365, 'Credo', 'Salsa', 'Salsa', '/video/365 Credo - Salsa.mp4'),
(366, 366, 'Todo Tiene Su Final', 'Hector Lavoe', 'Salsa', '/video/366 Todo tiene su Final - Salsa.mp4'),
(367, 367, 'Amnesia', 'Jose Jose', 'Balada / Romántica', '/video/367  José José  -Amnesia.mp4'),
(368, 368, 'Si Quieres', 'Juan Gabriel', 'Balada / Romántica', '/video/368  SI QUIERES - JUAN GABRIEL.mp4'),
(369, 369, 'Sin Poderte Hablar', 'Willi Colon', 'Salsa', '/video/369 WILLIE COLON - SIN PODERTE HABLAR.mp4'),
(370, 370, 'Amor Y Control', 'Ruben Blades', 'Variado / Éxitos', '/video/370  Amor y Control _ Rubén Blades.mp4'),
(371, 371, 'Si Tu Eres Mi Hombre Y Yo Tu Mujer', 'Your Band', 'Variado / Éxitos', '/video/371 Si tu eres mi hombre y yo tu mujer - The New York Band.mp4'),
(372, 372, 'Cataclismo', 'Javier Solis', 'Ranchera / Mariachi', '/video/372 Javier Solis - Cataclismo.mp4'),
(373, 373, 'Murio La Flor', 'Los Angeles Negros', 'Balada / Romántica', '/video/373  Los Ángeles Negros - Murió la flor.mp4'),
(374, 374, 'A Tu Recuerdo', 'Los Angeles Negros', 'Balada / Romántica', '/video/374 Los Angeles Negros - A Tu Recuerdo.mp4'),
(375, 375, 'Esta Noche La Paso Contigo', 'Los Angeles Negros', 'Balada / Romántica', '/video/375 Los Angeles Negros - Esta Noche La Paso Contigo.mp4'),
(376, 376, 'Que De Raro Tiene', 'Los Temerarios', 'Balada / Romántica', '/video/376 Los Temerarios - Que De Raro Tiene.mp4'),
(377, 377, 'Volvio El Dolor', 'Binomio De Oro', 'Vallenato', '/video/377 El Binomio De Oro - Volvio El Dolor.mp4'),
(378, 378, 'Al Paso', 'Dimension Latina', 'Salsa', '/video/378  Al paso Dimension Latina.mp4'),
(379, 379, 'El Profesor Rui Rua', 'Billos Caracas Boys', 'Merengue', '/video/379  Billos Caracas Boys  El Profesor Rui Rua.mp4'),
(380, 380, 'La Saporrita', 'Fruko', 'Salsa', '/video/380 FRUKO  LA SAPORRITA.mp4'),
(381, 381, 'Tengo Derecho A Ser Feliz', 'Junior Gonzalez', 'Salsa', '/video/381 Junior Gonzelez  tengo derecho a ser feliz salsa.mp4'),
(382, 382, 'La Burrita', 'Los Corrales De Majagual', 'Merengue', '/video/382  La burrita    Los Corraleros de Majagual.mp4'),
(383, 383, 'El Vampiro', 'Los Corrales De Majagual', 'Merengue', '/video/383 Los corraleros de Majagual  El Vampiro con coros.mp4'),
(384, 384, 'Mix La Avispa La Bartolera', 'Mix Los Blancos Y Master', 'Merengue', '/video/384 la avispa y la bartolera mix los blanco y los master juntos_480p.mp4'),
(385, 385, 'Corazon No Sufras Mas', 'Scarlett Linares', 'Música Llanera', '/video/385 CORAZON NO SUFRAS MAS - SCARLETT LINARES..mp4'),
(386, 386, 'El Reloj', 'Los Pasteles Verdes', 'Balada / Romántica', '/video/386 EL RELOJ - LOS PASTELES VERDES.mp4'),
(387, 387, 'El Loco', 'Los Pasteles Verdes', 'Balada / Romántica', '/video/387 EL LOCO - LOS PASTELES VERDES.mp4'),
(388, 388, 'Por El Amor A Mi Madre', 'Antonio Aguilar', 'Ranchera / Mariachi', '/video/388 Antonio Aguilar - Por El Amor A Mi Madre.mp4'),
(389, 389, 'Como Han Pasado Los Años', 'Rocio Durcal', 'Balada / Romántica', '/video/389 Cómo Han Pasado Los Años -  Rocío Dúrcal.mp4'),
(390, 390, 'Amada Amante', 'Roberto Carlos', 'Balada / Romántica', '/video/390 Amada Amante - Roberto Carlos.mp4'),
(391, 391, 'Candilejas', 'Jose Augusto', 'Variado / Éxitos', '/video/391 Candilejas -  José Augusto.mp4'),
(392, 392, 'Periodico De Ayer', 'Hector Lavoe', 'Salsa', '/video/392 Hector Lavoe - Periodico De Ayer.mp4'),
(393, 393, 'Inocente Pobre Amiga', 'Rocio Durcal', 'Balada / Romántica', '/video/393   Rocío Dúrcal - Inocente pobre amiga.mp4'),
(394, 394, 'Golpe Con Golpe', 'Pastor Lopez', 'Cumbia / Tropical', '/video/394 Pastor Lopez Golpe Con Golpe.mp4'),
(395, 395, 'Camionero', 'Roberto Carlos', 'Balada / Romántica', '/video/395 Camionero - Roberto Carlos.mp4'),
(396, 396, 'Celia', 'Leo Dan', 'Balada / Romántica', '/video/396 Leo Dan - Celia.mp4'),
(397, 397, 'Tu Me Pides Que Te Olvide', 'Leo Dan', 'Balada / Romántica', '/video/397 Leo Dan - Tu Me Pides Que Te Olvide.mp4'),
(398, 398, 'Niña Bonita', 'Binomio De Oro', 'Vallenato', '/video/398 Niña Bonita - Binomio De Oro.mp4'),
(399, 399, 'Olvidala', 'Binomio De Oro', 'Vallenato', '/video/399 Olvídala_ Binomio De Oro.mp4'),
(400, 400, 'Perdoname', 'Los Gigantes Del Vallenato', 'Vallenato', '/video/400 Perdóname_ Los Gigantes Del Vallenato.mp4'),
(401, 401, 'Preguntele A Su Hija', 'Fario Ortiz', 'Vallenato', '/video/401 Pregúntele a su hija- Farid Ortiz.mp4'),
(402, 402, 'Recuerdo De Un Amor', 'Los Diablitos', 'Vallenato', '/video/402 Recuerdos De Un Amor_ Los Diabitos.mp4'),
(403, 403, 'La Gata Bajo La Lluvia', 'Rocio Durcal', 'Balada / Romántica', '/video/403 Rocio Durcal - La Gata Bajo La Lluvia.mp4'),
(404, 404, 'Para Toda La Vida', 'Rocio Durcal', 'Balada / Romántica', '/video/404 Rocio Durcal - Para Toda La Vida.mp4'),
(405, 405, 'Tarde Lo Conoci', 'Patricia Teheran', 'Vallenato', '/video/405 Tarde lo conocí - Patricia Teherán - VALLENATO.mp4'),
(406, 406, 'Un Gato En La Oscuridad', 'Roberto Carlos', 'Balada / Romántica', '/video/406 Un Gato En La Obscuridad -Roberto Carlos.mp4'),
(407, 407, 'Detalles', 'Roberto Carlos', 'Balada / Romántica', '/video/407 Roberto Carlos - Detalles.mp4'),
(408, 408, 'No Entiendo', 'Ana Gabriel', 'Balada / Romántica', '/video/408 Ana Gabriel  No Entiendo.mp4'),
(409, 409, 'Mix Los Pasteles Verdes', 'Mix Pasteles Verdes Los Blancos', 'Merengue', '/video/409  Mix  Los Pasteles Verdes  Los Galos  Los Ángeles Negros.mp4'),
(410, 410, 'Y Como Es El', 'Jose Luis Perales', 'Balada / Romántica', '/video/410 Y como es el - Jose Luis Perales.mp4'),
(411, 411, 'Son Mentiras', 'Reyna Lucero', 'Variado / Éxitos', '/video/411 Reyna Lucero - Son Mentiras -.mp4'),
(412, 412, 'Por Amor', 'Jose Luis Perales', 'Balada / Romántica', '/video/412 Por Amor - Jose Luis Perales.mp4'),
(413, 413, 'Mi Cali Bella', 'Billos Caracas Boys', 'Merengue', '/video/413 Mi Cali Bella Billo_s Caracas Boys.mp4'),
(414, 414, 'Ariel', 'Billos Caracas Boys', 'Merengue', '/video/414  Ariel Billos Caracas Boys.mp4'),
(415, 415, 'La Negrita De Cheo', 'Billos Caracas Boys', 'Merengue', '/video/415  _La negrita de Cheo_ - Billos.mp4'),
(416, 416, 'El Pastorcillo', 'Los Melodicos', 'Merengue', '/video/416 EL PASTORCILLO- Loa Melodicos.mp4'),
(417, 417, 'El Amor', 'Jose Luis Perales', 'Balada / Romántica', '/video/417 El Amor - Jose Luis Perales.mp4'),
(418, 418, 'Cuando Florescan Las Amapolas', 'Los Blancos', 'Merengue', '/video/418 -Los Blanco Cuando Florescan Las Amapolas.mp4'),
(419, 419, 'Soy Castellana', 'Los Melodicos', 'Merengue', '/video/419 -SOY CASTELLANA- los melodicos.mp4'),
(420, 420, 'El Año Viejo', 'Tony Gamardo', 'Variado / Éxitos', '/video/420 Tony Camargo- El Año Viejo.mp4'),
(421, 421, 'Sonambulo', 'Fernandito Villalona', 'Merengue', '/video/421 sonambulo   fernandito villalona.mp4'),
(422, 422, 'Señora De Las 4 Decadas', 'Ricardo Arjona', 'Balada / Romántica', '/video/422 Señora De Las Cuatro Décadas -Arjona.mp4'),
(423, 423, 'Cuando Te Acuerde De Mi', 'Marco Antonio Solis', 'Balada / Romántica', '/video/423 Cuando Te Acuerdes De Mí - Marco Antonio Solís.mp4'),
(424, 424, 'Donde Estara Mi Primavera', 'Marco Antonio Solis', 'Balada / Romántica', '/video/424 Donde Estara Mi Primavera   Marco Antonio Solis.mp4'),
(425, 425, 'O Me Voy O Te Vas', 'Marco Antonio Solis', 'Balada / Romántica', '/video/425 Marco Antonio Solis - O Me Voy O Te Vas.mp4'),
(426, 426, 'Y Ahora Te Vas', 'Marco Antonio Solis', 'Balada / Romántica', '/video/426 Marco Antonio Solis - Y Ahora Te Vas.mp4'),
(427, 427, 'Tu Carcel', 'Marco Antonio Solis', 'Balada / Romántica', '/video/427 Tu Carcel - Marco Antonio Solis.mp4'),
(428, 428, 'Procuro Olvidarte', 'Pecos Kanvas', 'Balada / Romántica', '/video/428 PROCURO OLVIDARTE  - PECOS KANVAS.mp4'),
(429, 429, 'Ese Tipo Soy Yo', 'Roberto Carlos', 'Balada / Romántica', '/video/429 Ese tipo soy yo - Roberto Carlos.mp4'),
(430, 430, 'En Un Beso La Vida', 'Orlando Contreras', 'Balada / Romántica', '/video/430 Orlando Contreras En un beso la vida.mp4'),
(431, 431, 'Solamente Una Vez', 'Altemar Dutra', 'Balada / Romántica', '/video/431 Solamente una vez - Altemar Dutra.mp4'),
(432, 432, 'Cama Y Mesa', 'Roberto Carlos', 'Balada / Romántica', '/video/432 ROBERTO CARLOS - CAMA Y MESA.mp4'),
(433, 433, 'Historia De Un Amor', 'Varios', 'Variado / Éxitos', '/video/433 Historia De Un Amor -.mp4'),
(434, 434, 'Amigo', 'Roberto Carlos', 'Balada / Romántica', '/video/434 _ ROBERTO CARLOS  _ AMIGO.mp4'),
(435, 435, 'Candilejas', 'Roberto Carlos', 'Balada / Romántica', '/video/435 Roberto Carlos   Candilejas.mp4'),
(436, 436, 'Que De Raro Tiene', 'Vicente Fernandez', 'Ranchera / Mariachi', '/video/436 ¿Qué De Raro Tiene_  Vicente Fernández.mp4'),
(437, 437, 'Perdon', 'Vicente Fernandez', 'Ranchera / Mariachi', '/video/437 Perdón - Vicente Fernandez.mp4'),
(438, 438, 'Sublime Mujer', 'Vicente Fernandez', 'Ranchera / Mariachi', '/video/438 Sublime Mujer- Vicente Fernandez.mp4'),
(439, 439, 'Para Siempre', 'Vicente Fernandez', 'Ranchera / Mariachi', '/video/439 Vicente Fernández   Para Siempre.mp4'),
(440, 440, 'Como Te Extraño Mi Amor', 'Leo Dan', 'Balada / Romántica', '/video/440 Leo Dan - Como Te Extraño Mi Amor.mp4'),
(441, 441, 'Por Un Caminito', 'Leo Dan', 'Balada / Romántica', '/video/441 LEO DAN POR UN CAMINITO.mp4'),
(442, 442, 'Soy El Ladron De Tu Amor', 'Gualberto Ibarreto', 'Música Llanera', '/video/442 Gualberto Ibarreto - Soy el ladron de tu amor.mp4'),
(443, 443, 'El Loco', 'Javier Solis', 'Ranchera / Mariachi', '/video/443 Javier Solis - El Loco.mp4'),
(444, 444, 'Payaso', 'Javier Solis', 'Ranchera / Mariachi', '/video/444 Javier Solis - Payaso.mp4'),
(445, 445, 'Me Voy A Quitar De En Medio', 'Vicente Fernandez', 'Ranchera / Mariachi', '/video/445 Vicente Fernandez Me Voy A Quitar De En Medio Karaoke.mp4'),
(446, 446, 'Ella Y El', 'Jose Luis Perales', 'Balada / Romántica', '/video/446 Ella y El - Jose luis Perales.mp4'),
(447, 447, 'Ese Tipo Soy Yo En Salsa', 'Israel', 'Salsa', '/video/447 ESE TIPO SOY YO-EN SALSA ISRAEL LA LOBA.mp4'),
(448, 448, 'Ya Te Olvide', 'Rocio Durcal', 'Balada / Romántica', '/video/448 Rocio Durcal - Ya Te Olvide.mp4'),
(449, 449, 'Alma Llanera', 'Simon Diaz', 'Música Llanera', '/video/449 -Alma Llanera Simon Diaz.mp4'),
(450, 450, 'Me Llamas', 'Jose Luis Perales', 'Balada / Romántica', '/video/450 Me llamas - Jose Luis Perales.mp4'),
(451, 451, 'Cajon De Araura Apureño', 'Carrao De Palmarito', 'Música Llanera', '/video/451 -Cajón de Arauca Apureño - El Carrao de Palmarito.mp4'),
(452, 452, 'Caminito Verde', 'Simon Diaz', 'Música Llanera', '/video/452 Caminito Verde   Simon Diaz.mp4'),
(453, 453, 'Estar Enamorado', 'Rafael', 'Balada / Romántica', '/video/453 Raphael - Estar Enamorado.mp4'),
(454, 454, 'Esteros De Camaguan', 'Jose Vicente Torrealba', 'Variado / Éxitos', '/video/454 -ESTEROS DE CAMAGUAN_ J V TORREALBA.mp4'),
(455, 455, 'Fiesta En Elorza', 'Eneas Perdomo', 'Música Llanera', '/video/455 - Fiesta en Elorza - LLanera.mp4'),
(456, 456, 'Desahogo', 'Roberto Carlos', 'Balada / Romántica', '/video/456 desahogo karaoke roberto carlos(240P).mp4'),
(457, 457, 'Rosario', 'Hector Cabrera', 'Variado / Éxitos', '/video/457- Héctor Cabrera. Tema_ _Rosario.mp4'),
(458, 458, 'Feliz Cumpleaños Cristiano', 'Luis Silva', 'Música Llanera', '/video/458 - LUIS SILVA  FELIZ CUMPLEAÑOS CRISTIANO.mp4'),
(459, 459, 'Vestida De Garza Blanca', 'Pedro Rosa', 'Variado / Éxitos', '/video/459 Vestida De Garza Blanca - Pedro Rosa Caro.mp4'),
(460, 460, 'Te Solte La Rienda', 'Jose Alfredo Jimenez', 'Ranchera / Mariachi', '/video/460- José Alfredo Jiménez - Te solté la rienda.mp4'),
(461, 461, 'Media Vuelta', 'Jose Alfredo Jimenez', 'Ranchera / Mariachi', '/video/461 - José Alfredo Jiménez - Media vuelta.mp4'),
(462, 462, 'Dueño De Nada', 'Jose Luis Rodriguez', 'Balada / Romántica', '/video/462 Dueño De Nada -  Jose Luis Rodriguez.mp4'),
(463, 463, 'Señora Bonita', 'Jose Luis Rodriguez', 'Balada / Romántica', '/video/463 José Luis Rodriguez El Puma   Señora Bonita.mp4'),
(464, 464, 'Tu', 'Noelia', 'Variado / Éxitos', '/video/464 TU - Noelia.mp4'),
(465, 465, 'Noviembre Sin Ti', 'Reik', 'Pop Latino / Urbano', '/video/465 Noviembre sin ti - Reik.mp4'),
(466, 466, 'Tu Amor Por Siempre', 'Axel', 'Balada / Romántica', '/video/466 Tu Amor por siempre - Axel.mp4'),
(467, 467, 'Pero Me Acuerdo De Ti', 'Cristina Aguilera', 'Balada / Romántica', '/video/467 Pero me acuerdo de ti - Cristina Aguilera.mp4'),
(468, 468, 'Hasta El Fin Del Mundo', 'Jennifer Peña', 'Variado / Éxitos', '/video/468 Hasta el Fin del Mundo - Jennifer Peña.mp4'),
(469, 469, 'Se Fue', 'Laura Pausini', 'Balada / Romántica', '/video/469 Se fue - Laura Pausini.mp4'),
(470, 470, 'Amo', 'Axel', 'Balada / Romántica', '/video/470 Amo - Axel.mp4'),
(471, 471, 'En Cambio No', 'Laura Pausini', 'Balada / Romántica', '/video/471 En cambio no - Laura Pausini.mp4'),
(472, 472, 'Amores Extraños', 'Laura Pausini', 'Balada / Romántica', '/video/472 Amores Extraños - Laura Pausini.mp4'),
(473, 473, 'A Donde Va El Amor', 'Ricardo Montaner', 'Pop Latino / Urbano', '/video/473 A donde va el Amor - Ricardo Montaner.mp4'),
(474, 474, 'Tan Enamorados', 'Ricardo Montaner', 'Pop Latino / Urbano', '/video/474 Tan Enamorados - Ricardo Montaner.mp4'),
(475, 475, 'La Cima Del Cielo', 'Ricardo Montaner', 'Pop Latino / Urbano', '/video/475 La cima del cielo - Ricardo Montaner.mp4'),
(476, 476, 'Sera', 'Ricardo Montaner', 'Pop Latino / Urbano', '/video/476 Sera - Ricardo Montaner.mp4'),
(477, 477, 'Me Va Extrañar', 'Ricardo Montaner', 'Pop Latino / Urbano', '/video/477 Me va Extrañar - Ricardo Montaner.mp4'),
(478, 478, 'Destino', 'Greiccy', 'Pop Latino / Urbano', '/video/478 Destino - Greeicy.mp4'),
(479, 479, 'Mas Fuerte', 'Greiccy', 'Pop Latino / Urbano', '/video/479 Mas Fuerte - Greeicy.mp4'),
(480, 480, 'Quizas', 'Enrique Iglesias', 'Pop Latino / Urbano', '/video/480 Quizas - Enrique Iglesias.mp4'),
(481, 481, 'Cuando Me Enamoro', 'Enrique Iglesias', 'Pop Latino / Urbano', '/video/481 Cuando me Enamoro - Enrique Iglesias.mp4'),
(482, 482, 'Si Tu Te Vas', 'Enrique Iglesias', 'Pop Latino / Urbano', '/video/482 Si tu te vas - Enrique Iglesias.mp4'),
(483, 483, 'Nunca Te Olvidare', 'Enrique Iglesias', 'Pop Latino / Urbano', '/video/483 Nunca te Olvidare - Enrique Iglesias.mp4'),
(484, 484, 'Bailando', 'Enrique Iglesias', 'Pop Latino / Urbano', '/video/484 Bailando - Enrique Iglesias.mp4'),
(485, 485, 'Labios Compartidos', 'Mana', 'Rock / Pop-Rock', '/video/485 Labios Compartidos - Mana.mp4'),
(486, 486, 'En El Muelle De San Blas', 'Mana', 'Rock / Pop-Rock', '/video/486 En el Muelle de San Blas - Mana.mp4'),
(487, 487, 'El Reloj Cucu Sonaba', 'Mana', 'Rock / Pop-Rock', '/video/487 el reloj cucu - Mana.mp4'),
(488, 488, 'Clavado En Un Bar', 'Mana', 'Rock / Pop-Rock', '/video/488 Clavado en un Bar - Mana.mp4'),
(489, 489, 'Justicia', 'Silvestre Y Natty Natacha', 'Vallenato', '/video/489 Justicia - Silvestre y Natti Natacha.mp4'),
(490, 490, 'Cuatro Rosas', 'Jorge Celedon', 'Vallenato', '/video/490 Cuatro Rosas - Jorge Celedon.mp4'),
(491, 491, 'Materialista', 'Silvestre', 'Vallenato', '/video/491 Materialista - Silvestre.mp4'),
(492, 492, 'Quien Sera', 'Sonora Matansera', 'Cumbia / Tropical', '/video/492 Quien sera - Sonora Matancera.mp4'),
(493, 493, 'Dulce Pecado', 'Jessi Uribe', 'Ranchera / Mariachi', '/video/493 Dulce Pecado - Jessi Uribe.mp4'),
(494, 494, 'Darte Un Beso', 'Prince Royce', 'Pop Latino / Urbano', '/video/494 Darte un Beso - Prince Royce.mp4'),
(495, 495, 'Un Dos Tres', 'Simbolo', 'Variado / Éxitos', '/video/495 Un Dos Tres - Simbolo.mp4'),
(496, 496, 'Amor Narcotico', 'Chichi Peralta', 'Merengue', '/video/496 Amor Narcotico - Chichi Peralta.mp4'),
(497, 497, 'No Podras', 'Cristian Castro', 'Balada / Romántica', '/video/497 No podras - Cristian Castro.mp4'),
(498, 498, 'La Vida Es Un Carnaval', 'Celia Cruz', 'Variado / Éxitos', '/video/498 La Vida es un Carnaval - Celia Cruz.mp4'),
(499, 499, 'La Negra Tomasa', 'Caifanes', 'Rock / Pop-Rock', '/video/499 La Negra Tomasa - Caifanes.mp4'),
(500, 500, 'Cosas De La Vida', 'Eros Ramazotti', 'Variado / Éxitos', '/video/500 Cosas de la Vida - Eros Ramazotti.mp4'),
(501, 501, 'Despechada', 'Rosalia', 'Pop Latino / Urbano', '/video/501 Despechada - Rosalia.mp4'),
(502, 502, 'Quien', 'Pedrito Fernandez', 'Ranchera / Mariachi', '/video/502 Quien - Pedrito Fernandez.mp4'),
(503, 503, 'Yo No Fui', 'Pedrito Fernandez', 'Ranchera / Mariachi', '/video/503 Yo no Fui - Pedrito Fernandez.mp4'),
(504, 504, 'Cumpleaños Feliz', 'Luis Cruz', 'Balada / Romántica', '/video/504 Cumpleaños feliz.mp4'),
(505, 505, 'Me Hace Daño Verte', 'Salsa', 'Salsa', '/video/505 Me hace daño verte.mp4'),
(506, 506, 'Una Aventura', 'Grupo Niche', 'Salsa', '/video/506 Una Aventura - Grupo Niche.mov'),
(507, 507, 'Te He Prometido Salsa', 'Leo Dan', 'Salsa', '/video/507 Te he Prometido - Salsa -Leo Dan.mov'),
(508, 508, 'Te Compro Tu Novia', 'Ramon Orlando', 'Variado / Éxitos', '/video/508 Te compro tu Novia -.mov'),
(509, 509, 'Que Bonito Es El Querer', 'Memo Morales', 'Variado / Éxitos', '/video/509 Que bonito es el querer -  Memo Morales -  Karaoke(240P)(360P).mp4'),
(510, 510, 'Por Mujeres Como Tu', 'Pepe Aguilar', 'Ranchera / Mariachi', '/video/510 Por Mujeres como Tu - Pepe Aguilar.mov'),
(511, 511, 'Me Vas A Extrañar', 'Pepe Aguilar', 'Ranchera / Mariachi', '/video/511 Me vas a Extrañar - Pepe Aguilar.mov'),
(512, 512, 'Mi Promesa', 'Memo Morales', 'Variado / Éxitos', '/video/512 mi promesa paso doble   memo morales(360P).mp4'),
(513, 513, 'Trigal', 'Sandro', 'Balada / Romántica', '/video/513 Trigal,  Sandro karaoke.mp4'),
(514, 514, 'El Ferry', 'Gaiteros Pillopo', 'Variado / Éxitos', '/video/514 El ferry gaiteros del pillopo by castor karaoke show.mp4'),
(515, 515, 'Nunca Es Tarde Para Amar', 'Rincon Morales', 'Variado / Éxitos', '/video/515  NUNCA ES TARDE PARA AMAR RINCON MORALES.mp4'),
(516, 516, 'Homenaje Miguel Moly', 'Miguel Moly', 'Merengue', '/video/516 homenaje a miguel moly by castor karaoke show.mp4'),
(517, 517, 'Junto A Tu Corazon', 'Miguel Moly', 'Merengue', '/video/517 Junto a tu corazón, Miguel Moly.mp4'),
(518, 518, 'Mi Corazon Es Un Gitano', 'Nicola Di Bari', 'Balada / Romántica', '/video/518 Nicola Di Bari - Mi Corazon Es Un Gitano.mp4'),
(519, 519, 'La Copa Rota', 'Jose Feliciano', 'Balada / Romántica', '/video/519 Jose Feliciano - La Copa Rota.mp4'),
(520, 520, 'Yo Te Amo.', 'Sandro', 'Balada / Romántica', '/video/520 Yo Te Amo - Sandro.mp4'),
(521, 521, 'Despierta', 'Pedro Infante', 'Ranchera / Mariachi', '/video/521 Pedro Infante - Despierta.mp4'),
(522, 522, 'Los Terricolas', 'Nuestra Historia', 'Balada / Romántica', '/video/522 NUESTRA HISTORIA - LOS TERRICOLAS.mp4'),
(523, 523, 'Danny Rivera', 'Mujer Abre Tu Ventana', 'Balada / Romántica', '/video/523 MUJER ABRE TU VENTANA - DANNY RIVERA.mp4'),
(524, 524, 'Vicente Fernandez Y Alejando', 'Perdon', 'Ranchera / Mariachi', '/video/524 PERDON - VICENTE FERNANDEZ Y ALEJANDO.mp4'),
(525, 525, 'Emilio Jose', 'Nuestra Playa', 'Variado / Éxitos', '/video/525 NUESTRA PLAYA - EMILIO JOSE.mp4'),
(526, 526, 'Yiyo Sarante', 'Que Agonia', 'Variado / Éxitos', '/video/526 QUE AGONIA - YIYO SARANTE.mp4'),
(527, 527, 'Cristian Nodal', 'Probablemente Salsa', 'Salsa', '/video/527 PROBABLEMENTE SALSA - CRISTIAN NODAL.mp4'),
(528, 528, 'Luis Silva Gaita', 'Amor Del Bueno', 'Música Llanera', '/video/528 AMOR DEL BUENO - LUIS SILVA GAITA.mov'),
(529, 529, 'Haremos El Amor', 'Tony Vega', 'Salsa', '/video/529 Tony Vega - Haremos el amor.mp4'),
(530, 530, 'Yordano', 'En Aquel Lugar Secreto', 'Balada / Romántica', '/video/530 EN AQUEL LUGAR SECRETO -  Yordano (240P).mp4'),
(531, 531, 'Fantasía Herida', 'Erick Franchesky', 'Variado / Éxitos', '/video/531 Erick Franchesky -Fantasía Herida.mp4'),
(532, 532, 'Jesús Adrián Romero', 'Princesas Magicas', 'Variado / Éxitos', '/video/532 Princesas Magicas - Jesús Adrián Romero(240P).mp4'),
(533, 533, 'Christian Nodal', 'Probablemente', 'Ranchera / Mariachi', '/video/533 Probablemente - Christian Nodal(240P).mp4'),
(534, 534, 'Castor', 'Homenaje A Javier Solis', 'Ranchera / Mariachi', '/video/534 homenaje a javier solis - castor.mp4'),
(535, 535, 'Amnesia Version Mariachi', 'Desconocido', 'Variado / Éxitos', '/video/535 amnesia version mariachi(360P).mp4'),
(536, 536, 'Rafael El Pollo Brito', 'El Parrandon', 'Variado / Éxitos', '/video/536 El parrandon - rafael el pollo brito.mp4'),
(537, 537, 'Homenaje A Gualberto Ibarreto', 'Desconocido', 'Música Llanera', '/video/537  homenaje a gualberto ibarreto(240P).mp4'),
(538, 538, 'Homenaje A Pastor Lopez Free Cover Venezuela Ft Pollo Brito', 'Desconocido', 'Cumbia / Tropical', '/video/538 homenaje a pastor lopez free cover venezuela ft pollo brito(240P).mp4'),
(539, 539, 'Ignacio Rondon Señora Yo Quiero Un Beso', 'Desconocido', 'Música Llanera', '/video/539 Ignacio Rondon Señora yo Quiero un Beso(360P).mp4'),
(540, 540, 'Ricardo Y Luna Montaner', 'La Gloria De Dios', 'Variado / Éxitos', '/video/540 la gloria de Dios -  ricardo y luna montaner(360P).mp4'),
(541, 541, 'Guaco', 'Lo Eres Todo', 'Variado / Éxitos', '/video/541 lo eres todo -    Guaco.mp4'),
(542, 542, 'Reynaldo Armas.', 'Los Primeros Días De Abril', 'Música Llanera', '/video/542 LOS PRIMEROS DÍAS DE ABRIL-  REYNALDO ARMAS..mp4'),
(543, 543, 'Mauricio Silva', 'Mix Exitos Salsa', 'Salsa', '/video/543 Mix exitos salsa   - mauricio silva.mp4'),
(544, 544, 'Castor', 'Mix Merengue Del Recuerdo', 'Merengue', '/video/544 Mix merengue del recuerdo - castor.mp4'),
(545, 545, 'Merengue', 'Todo Me Gusta De Tí', 'Merengue', '/video/545 Todo me gusta de tí - Merengue.mp4'),
(546, 546, 'Reynaldo Armas', 'La Inspiración Del Poeta', 'Música Llanera', '/video/546 La Inspiración del Poeta - Reynaldo Armas -.mp4'),
(547, 547, 'Tommy Olivencia', 'Lobo Domesticado', 'Salsa', '/video/547 Lobo domesticado - Tommy Olivencia (salsa).mp4'),
(548, 548, 'Galy Galiano', 'Me Bebí Tu Recuerdo', 'Variado / Éxitos', '/video/548 Me Bebí Tu Recuerdo - Galy Galiano.mp4'),
(549, 549, 'Guaco', 'Pideme', 'Variado / Éxitos', '/video/549 Pideme -Guaco.mp4'),
(550, 550, 'Gilberto Santarosa', 'Que Alguien Me Diga', 'Variado / Éxitos', '/video/550 Que Alguien Me Diga - Gilberto Santarosa.mp4'),
(551, 551, 'Corazón En Blanco', 'Roberto Lugo', 'Variado / Éxitos', '/video/551 Roberto Lugo  -  Corazón en blanco.mp4'),
(552, 552, 'Fernandito Villalona', 'Se Que Te Perdí', 'Merengue', '/video/552 Se que te perdí - Fernandito Villalona.mp4'),
(553, 553, 'Vicente Fernández', 'Tengo Una Amante', 'Variado / Éxitos', '/video/553 Tengo Una Amante - Vicente Fernández.mp4'),
(554, 554, 'Reynaldo Armas', 'Tierra Bendita', 'Música Llanera', '/video/554 Tierra Bendita - Reynaldo Armas.mp4'),
(555, 555, 'El Hombre Que Más Te Amo', 'Vicente Fernandez', 'Ranchera / Mariachi', '/video/555 Vicente Fernandez  - El Hombre Que Más Te Amo.mp4'),
(556, 556, 'Tengo Ganas', 'Victor Manuelle', 'Variado / Éxitos', '/video/556 Victor Manuelle  - Tengo ganas.mp4'),
(557, 557, 'Si Tu Me Besas', 'Victor Manuelle', 'Variado / Éxitos', '/video/557 Victor Manuelle - Si tu me besas.mp4')
ON CONFLICT (numero) DO UPDATE SET titulo = EXCLUDED.titulo, artista = EXCLUDED.artista, genero = EXCLUDED.genero, video_url = EXCLUDED.video_url;

-- Ajustar secuencia
SELECT setval('canciones_id_seq', coalesce((SELECT max(id) + 1 FROM canciones), 1), false);